services:
  - type: web
    name: health-focus-clinics
    env: python
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn app:app --chdir backend
    autoDeploy: true

    envVars:
      - key: FLASK_ENV
        value: production
